services:
  react:
    build:
      context: ./material_kit
      dockerfile: Dockerfile
    container_name: material-kit
    ports:
      - "3000:3000"
    volumes:
      - './material_kit:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://laravel:80
